### ISSUE TITLE
graphics error (?) when loading a deck in-game

### ISSUE THREAD

**Issue by brine** [octgn/OCTGN#1328]
user reported an error message saying "A Graphics object cannot be created from an image that has an indexed pixel format." error when trying to load a deck in-game.  http://hastebin.com/mekemodipi

```
 ERROR 2014-10-12 13:48:52,037 3.1.153.338 [1] Octgn.ViewModels.HostedGameViewModel [(null)] - Can't set UserImage to Uri
 System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at MS.Win32.WinInet.get_InternetCacheFolder()
   at System.Windows.Media.Imaging.BitmapDownload.BeginDownload(BitmapDecoder decoder, Uri uri, RequestCachePolicy uriCachePolicy, Stream stream)
   at System.Windows.Media.Imaging.LateBoundBitmapDecoder..ctor(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy requestCachePolicy)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at System.Windows.Media.Imaging.BitmapImage..ctor(Uri uriSource, RequestCachePolicy uriCachePolicy)
   at Octgn.ViewModels.HostedGameViewModel.Update(HostedGameViewModel newer, Game[] games) in c:\Program Files (x86)\Jenkins\workspace\OCTGN-Release\octgnFX\Octgn\ViewModels\HostedGameViewModel.cs:line 460
ERROR 2014-10-12 13:48:52,056 3.1.153.338 [1] Octgn.ViewModels.HostedGameViewModel [(null)] - Can't set UserImage to Uri
```

**Comment by Soul1355** [comment]
has anyone encountered this error recently? there's a good chance it was resolved when click-through transparency was added.
