### ISSUE TITLE
Mac // Disconnection Issues // Window won't go away

### ISSUE THREAD

**Issue by domtancredi** [octgn/OCTGN#1484]
I get plagued with disconnect/reconnect issues, on a Mac using Wine, version 3.1.202.0

However, sometimes I can use key-commands, and, if I'm "disconnected/reconnected" still chat. So I think the modal overlay needs to be dismissed and it's not.

Is there a way to manually dismiss that modal overlay? Or add a button to manually "check for reconnection"? I think if it just checks one more time, it'll know I AM connected...

**Comment by jgahura** [comment]
I have the same problem. In the log, the endless reconnecting starts like this (the WARN is then repeated infinitely):
```
WARN  2015-10-20 22:42:05,157 3.1.231.0 [16] Octgn.Networking.ClientSocket [(null)] - EndReceive
 System.Net.Sockets.SocketException (0x80004005): Semaphore timeout
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at Octgn.Library.Networking.SocketBase.EndReceive(IAsyncResult res) in c:\projects\octgn\octgnFX\Octgn.Library\Networking\SocketBase.cs:line 157
DEBUG 2015-10-20 22:42:05,360 3.1.231.0 [16] Octgn.Networking.ClientSocket [(null)] - OnDisconnect
 DEBUG 2015-10-20 22:42:05,363 3.1.231.0 [16] Octgn.Networking.ClientSocket [(null)] - CallOnConnectionEvent Disconnected
 DEBUG 2015-10-20 22:42:05,366 3.1.231.0 [16] Octgn.Networking.ClientSocket [(null)] - OnConnectionEvent Disconnected
 ERROR 2015-10-20 22:42:05,368 3.1.231.0 [16] Octgn.Networking.ClientSocket [(null)] - Disconnect Event 96.31.76.45:12952
 DEBUG 2015-10-20 22:42:05,370 3.1.231.0 [1] Octgn.GameEngine [(null)] - IsConnected = False
 DEBUG 2015-10-20 22:42:05,370 3.1.231.0 [21] Octgn.Networking.ClientSocket [(null)] - DoReconnect
 DEBUG 2015-10-20 22:42:05,373 3.1.231.0 [21] Octgn.Networking.ClientSocket [(null)] - DoReconnect Trying to reconnect
 DEBUG 2015-10-20 22:42:05,375 3.1.231.0 [21] Octgn.Networking.ClientSocket [(null)] - Connect
 DEBUG 2015-10-20 22:42:06,066 3.1.231.0 [17] Octgn.Networking.ClientSocket [(null)] - StartPings Done Pinging
 INFO  2015-10-20 22:42:15,562 3.1.231.0 [16] Octgn.Utils.SSLValidationHelper [(null)] - SSL Request
 INFO  2015-10-20 22:42:15,564 3.1.231.0 [16] Octgn.Utils.SSLValidationHelper [(null)] - Ignoring SSL Validation
 INFO  2015-10-20 22:42:32,656 3.1.231.0 [14] Octgn.Utils.SSLValidationHelper [(null)] - SSL Request
 INFO  2015-10-20 22:42:32,659 3.1.231.0 [14] Octgn.Utils.SSLValidationHelper [(null)] - Ignoring SSL Validation
 INFO  2015-10-20 22:42:49,709 3.1.231.0 [4] Octgn.Utils.SSLValidationHelper [(null)] - SSL Request
 INFO  2015-10-20 22:42:49,712 3.1.231.0 [4] Octgn.Utils.SSLValidationHelper [(null)] - Ignoring SSL Validation
 INFO  2015-10-20 22:43:07,233 3.1.231.0 [15] Octgn.Utils.SSLValidationHelper [(null)] - SSL Request
 INFO  2015-10-20 22:43:07,237 3.1.231.0 [15] Octgn.Utils.SSLValidationHelper [(null)] - Ignoring SSL Validation
 WARN  2015-10-20 22:43:20,865 3.1.231.0 [21] Octgn.Networking.ClientSocket [(null)] - DoReconnect
 System.Net.Sockets.SocketException (0x80004005): Unknown error (0x274c) 96.31.76.45:12952
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at Octgn.Library.Networking.SocketBase.Connect() in c:\projects\octgn\octgnFX\Octgn.Library\Networking\SocketBase.cs:line 79
   at Octgn.Library.Networking.ReconnectingSocketBase.DoReconnect() in c:\projects\octgn\octgnFX\Octgn.Library\Networking\ReconnectingSocketBase.cs:line 82
DEBUG 2015-10-20 22:43:21,869 3.1.231.0 [21] Octgn.Networking.ClientSocket [(null)] - DoReconnect Trying to reconnect
 DEBUG 2015-10-20 22:43:21,873 3.1.231.0 [21] Octgn.Networking.ClientSocket [(null)] - Connect
 WARN  2015-10-20 22:43:21,874 3.1.231.0 [21] Octgn.Networking.ClientSocket [(null)] - DoReconnect
 System.Net.Sockets.SocketException (0x80004005): Unknown error (0x2726) 96.31.76.45:12952
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at Octgn.Library.Networking.SocketBase.Connect() in c:\projects\octgn\octgnFX\Octgn.Library\Networking\SocketBase.cs:line 79
   at Octgn.Library.Networking.ReconnectingSocketBase.DoReconnect() in c:\projects\octgn\octgnFX\Octgn.Library\Networking\ReconnectingSocketBase.cs:line 82
DEBUG 2015-10-20 22:43:22,877 3.1.231.0 [21] Octgn.Networking.ClientSocket [(null)] - DoReconnect Trying to reconnect
 DEBUG 2015-10-20 22:43:22,880 3.1.231.0 [21] Octgn.Networking.ClientSocket [(null)] - Connect
 WARN  2015-10-20 22:43:22,882 3.1.231.0 [21] Octgn.Networking.ClientSocket [(null)] - DoReconnect
 System.Net.Sockets.SocketException (0x80004005): Unknown error (0x2726) 96.31.76.45:12952
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at Octgn.Library.Networking.SocketBase.Connect() in c:\projects\octgn\octgnFX\Octgn.Library\Networking\SocketBase.cs:line 79
   at Octgn.Library.Networking.ReconnectingSocketBase.DoReconnect() in c:\projects\octgn\octgnFX\Octgn.Library\Networking\ReconnectingSocketBase.cs:line 82
DEBUG 2015-10-20 22:43:23,886 3.1.231.0 [21] Octgn.Networking.ClientSocket [(null)] - DoReconnect Trying to reconnect
 DEBUG 2015-10-20 22:43:23,889 3.1.231.0 [21] Octgn.Networking.ClientSocket [(null)] - Connect
 WARN  2015-10-20 22:43:23,891 3.1.231.0 [21] Octgn.Networking.ClientSocket [(null)] - DoReconnect
 System.Net.Sockets.SocketException (0x80004005): Unknown error (0x2726) 96.31.76.45:12952
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at Octgn.Library.Networking.SocketBase.Connect() in c:\projects\octgn\octgnFX\Octgn.Library\Networking\SocketBase.cs:line 79
   at Octgn.Library.Networking.ReconnectingSocketBase.DoReconnect() in c:\projects\octgn\octgnFX\Octgn.Library\Networking\ReconnectingSocketBase.cs:line 82
```

**Comment by jgahura** [comment]
Any chance to get it fixed? Thanks.

**Comment by Soul1355** [comment]
just to say you're not being ignored, I wanted to explain that the chat and the game connect separately, and because it was added after the whole application was built, the re-connection is a somewhat complicated process, which is why it's been a struggle to get all the bugs ironed out.

**Comment by jgahura** [comment]
Thanks for the reply. I have maybe a workaround to this problem. I play LOTR LCG alone. I've created a second account and create a game for two player. In this case, the second player keeps the game state so I have something to reconnect to.

**Comment by Soul1355** [comment]
Oh, that's kinda a sperate issue if you're playing alone, but the simplest solution in that case is that you can play offline by either not signing in or if you enable advanced options there is a checkbox when creating the game to play locally.

**Comment by jgahura** [comment]
Great! I didn't know that. Unfortunately, it doesn't work on Mac. I'm getting this in the log:
WARN   3.1.235.0 [12] Octgn.Controls.HostGameSettings [(null)] - Start Game Error
 System.AggregateException: One or more errors occurred. ---> System.Net.NetworkInformation.NetworkInformationException: Request not supported
   at System.Net.NetworkInformation.SystemIPGlobalProperties.GetAllTcpConnections()
   at System.Net.NetworkInformation.SystemIPGlobalProperties.GetActiveTcpConnections()
   at Skylabs.Lobby.Networking.IsPortAvailable(Int32 port) in c:\projects\octgn\octgnFX\Skylabs.Lobby\Networking.cs:line 16
   at Octgn.Controls.HostGameSettings.StartLocalGame(Game game, String name, String password) in c:\projects\octgn\octgnFX\Octgn\Controls\HostGameSettings.xaml.cs:line 245
   at Octgn.Controls.HostGameSettings.<ButtonHostGameStartClick>b__a() in c:\projects\octgn\octgnFX\Octgn\Controls\HostGameSettings.xaml.cs:line 316
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.NetworkInformation.NetworkInformationException (0x80004005): Request not supported
   at System.Net.NetworkInformation.SystemIPGlobalProperties.GetAllTcpConnections()
   at System.Net.NetworkInformation.SystemIPGlobalProperties.GetActiveTcpConnections()
   at Skylabs.Lobby.Networking.IsPortAvailable(Int32 port) in c:\projects\octgn\octgnFX\Skylabs.Lobby\Networking.cs:line 16
   at Octgn.Controls.HostGameSettings.StartLocalGame(Game game, String name, String password) in c:\projects\octgn\octgnFX\Octgn\Controls\HostGameSettings.xaml.cs:line 245
   at Octgn.Controls.HostGameSettings.<ButtonHostGameStartClick>b__a() in c:\projects\octgn\octgnFX\Octgn\Controls\HostGameSettings.xaml.cs:line 316
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

I works on Windows ok.

**Comment by Soul1355** [comment]
Oh, that's too bad, glad you have something that does work at least, and hopefully we can get it working better

**Comment by brine** [comment]
closing WINE-related tickets since a lot would have changed since then
