### ISSUE TITLE
octgn crashes when you cancel a join game window

### ISSUE THREAD

**Issue by brine** [octgn/OCTGN#1727]
FATAL 2018-01-29 00:03:37,641 3.2.50.0 [1] Octgn.OctgnApp [(null)] - UNHANDLED EXCEPTION 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at Octgn.Tabs.Play.PlayTab.ConnectOfflineGameDialogOnClose(Object sender, DialogResult dialogResult) in C:\projects\octgn\octgnFX\Octgn\Tabs\Play\PlayTab.xaml.cs:line 363
   at Octgn.Controls.ConnectOfflineGame.ButtonCancelClick(Object sender, RoutedEventArgs e) in C:\projects\octgn\octgnFX\Octgn\Controls\ConnectOfflineGame.xaml.cs:line 184
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()

**Comment by brine** [comment]
doesn't happen anymore .  Possibly got coincidentally fixed when all the wires were hooked back up for the jodsengine split.

Will open a new ticket if it is re-discovered
