### ISSUE TITLE
Calling alternateProperty in a script will trigger a "KeyError: The given key was not present in the dictionary."

### ISSUE THREAD

**Issue by wlk0** [octgn/OCTGN#1778]
Calling alternateProperty in a script will trigger a "KeyError: The given key was not present in the dictionary." exception when the alternate is not defined for the card.
Example: `card.alternateProperty("B","Text")`

Exception in card.cs on line 590 (card has no "B" alternate version in that case): 
`var prop = _type.Model.Properties[alternate].Properties.FirstOrDefault(x => x.Key.Name.Equals(name, scompare));`

Apparently introduced by this commit: https://github.com/octgn/OCTGN/commit/f3d436238dcce90e0925c1ae874785f95ed243f9
Suggesting adding a `if(_type.Model.Properties.ContainsKey(alternate))` condition.

**Comment by brine** [comment]
quick executive decision here -- This issue properly throws a python exception in the chat and does not crash the game:

```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 293, in alternateProperty
KeyError: The given key was not present in the dictionary.

c.alternateProperty("flips", "Type")```

Moving forward with the API, especially with an upcoming revision being planned, should we be catching these sorts of errors and handling them without throwing exception messages?  I think we should be keeping them around as its technically an invalid argument being passed through the API, but there are many instances where the API catches and returns null values when an invalid argument is given.  Some sort of consistency should be decided.

**Comment by kellyelton** [comment]
I think we should throw errors in almost all situations.

**Comment by kellyelton** [comment]
I think we should throw errors with a useful message though.

In this case instead of `KeyError: The given key was not present in the dictionary.` we should throw something like `Alternate 'B' not found`

**Comment by kellyelton** [comment]
Based on #1865 , we should throw a specific error here instead of that generic one.
