### ISSUE TITLE
Crash when using Shift + Tab in deck builder

### ISSUE THREAD

**Issue by Otep3210** [octgn/OCTGN#2012]
Crashes in deck builder with shift + tab after loading a search.

**Comment by BenMatteson** [comment]
I can't reproduce this, can you be more detailed in reproduction steps? what part was the last thing that was clicked before pressing the hotkey? does the game have player and/or global deck sections defined? which of these tabs is selected when the crash occurs? does it require searching by name/set/other property?

**Comment by Otep3210** [comment]
I started a new deck, loaded a search and added a couple cards. Loaded another search added a couple cards then hit shift tab and it closes seems to do it.

**Comment by BenMatteson** [comment]
I've tried a few times and still can't seem to reproduce this crash; if you can still cause it, please drop by our discord and we can get your logs which should give us some idea of what's happening, because currently I'm stumped.

**Comment by Otep3210** [comment]
Sorry about the late reply on this, I made you a video. I am also on the Discord under Mitch quite often in game development.

https://youtu.be/Yj4tAoFg3mI

**Comment by BenMatteson** [comment]
The error
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Octgn.DeckBuilder.SearchControl.ResultKeyDownHandler(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSG& msg, Boolean& handled)
   at System.Windows.Interop.ThreadMessageEventHandler.Invoke(MSG& msg, Boolean& handled)
   at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Octgn.OctgnApp.Main()
```
