### ISSUE TITLE
"Join Unlisted Game" weird behavior (test v324)

### ISSUE THREAD

**Issue by brine** [octgn/OCTGN#2080]
When clicking the "Join Unlisted Game" button, the following error occurs.  Doesn't matter if there's actually a hosted local game or not.

Octgn.Library.Exceptions.UserMessageException: Error loading Environment: Invalid game CreatedDate is too ancient 1/1/0001 12:00:00 AM +00:00 ---> Octgn.Library.Exceptions.UserMessageException: Invalid game CreatedDate is too ancient 1/1/0001 12:00:00 AM +00:00
   at Octgn.CommandLineHandler.Validate(HostedGame hostedGame)
   at Octgn.CommandLineHandler.HandleArguments(String[] args)
   at Octgn.Loaders.EnvironmentLoader.LoadSync()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Octgn.Loaders.Loader.<Load>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at Octgn.Loaders.Loader.<Load>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octgn.Windows.LoadingWindow.<OnWindowLoaded>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by brine** [comment]
I checked this one out, and went down a rabbit hole.  This is supposed to be the direct IP connect option for joining games but it looks like the move to the jodsengine design broke most of this functionality?
